spring:
  application:
    name: fyke-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/fyke
    username: fyke
    password: fyke
  profiles:
    default: rabbitmq

fyke:
  enabled: true
  outbox:
    enabled: true
    poll-interval: 200ms
    batch-size: 50
    retention:
      enabled: true
      ttl: 7d

  inbox:
    enabled: true
    poll-interval: 200ms
    batch-size: 50
    initial-backoff: 500ms
    retention:
      enabled: true
      ttl: 7d

  dlq:
    retention:
      enabled: true
      ttl: 30d

  retention:
    enabled: true
  control-plane:
    enabled: true
    app-name: "${spring.application.name}"
    instance-id: "${HOSTNAME}-${random.uuid}"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    fyke:
      access: UNRESTRICTED
