spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.kafka.autoconfigure.KafkaAutoConfiguration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 50ms

fyke:
  binder: rabbitmq

demo:
  destination: events.exchange
  inbox-destination: orders.inbox.queue
  target: orders.created
